robot:
  class_name: Go2Robot
  friction: 0.75
  llc_dt: 0.001
  controller_dt: 0.005

controller:
  class_name: QuadrupedWBC
  gait_params:
    des_height: 0.325
    step_time: 0.25
    step_height: 0.05

  raibert_params:
    step_kd: [0.05,0.05]
    step_clip: [0.5,0.5]

  wbqp_targets_stand:
    body_orientation: 
      Kp: [400., 400., 400.]
      Kd: [20., 20., 20.]
      weights: [1.e+4,1.e+4,1.e+4]
    body_translation:
      Kp: [200., 200., 200.]
      Kd: [20., 20., 20.]
      weights: [1.e+4,1.e+4,1.e+4]
    
  wbqp_targets_walk:
    body_orientation: 
      Kp: [400., 400., 0.]
      Kd: [20., 20., 10.]
      weights: [1.e+4,1.e+4,1.e+4]
    body_translation:
      Kp: [0., 0., 200.]
      Kd: [10., 20., 20.]
      weights: [1.e+4,1.e+4,1.e+4]

  swing_params:
    Kp: 25.
    Kd: 1.

  stance_params:
    Kd: 1.

  wbqp_params:
    mu: 0.5
    friction_cone_order: 8
    actuation_cost: 1.
    contact_cost: 0.
    foot_on_ground_cost: 1.e+6
    swing_foot_tracking_cost: 1.e+4
    kin_constraint_cost: 1.e+6
    reqularizing_cost: 1.e-6
    delta_cost: 1.e+1
    tau_filter_alpha: 0.5
    kb: 0.

observer:
  class_name: InekfObserver
  encoder_noise: 0.001
  gyro_noise: 10.
  gyro_bias: 0.0
  accel_noise: 10.
  accel_bias: 0.0
  contact_noise: 10.
  foot_offset: 0.025
  add_visualizer: True

target:
  class_name: JoystickInput
  x_y_yaw_offset: [0.,0.,0.]
  x_y_yaw_scale: [-1.0,-0.5,-1.5]
  alpha_filter: 0.9
