robot:
  class_name: Go2Robot
  friction: 0.5
  llc_dt: 0.001
  controller_dt: 0.01

controller:
  class_name: QuadrupedWBC
  gait_params:
    des_height: 0.325
    step_time: 0.2
    step_height: 0.05

  raibert_params:
    step_kd: [0.05,0.05]
    step_clip: [0.5,0.5]
    com_kd: [10.,20.]

  wbqp_targets:
    body_orientation: 
      Kp: [400., 400., 0.]
      Kd: [20., 20., 10.]
      weights: [1.e+4,1.e+4,1.e+4]
    body_translation:
      Kp: [100., 100., 200.]
      Kd: [10., 10., 20.]
      weights: [1.e+4,1.e+4,1.e+4]
    
  swing_params:
    Kp: 25.
    Kd: 1.

  wbqp_params:
    mu: 0.5
    friction_cone_order: 8
    actuation_cost: 1.
    contact_cost: 0.
    foot_on_ground_cost: 1.e+6
    kin_constraint_cost: 1.e+6
    reqularizing_cost: 1.e-6
    delta_cost: 1.e+1
    tau_filter_alpha: 0.5
    kb: 0.

target:
  class_name: JoystickInput
  x_y_yaw_offset: [0.,0.,0.]
  x_y_yaw_scale: [-1.0,-0.5,-1.5]
  alpha_filter: 0.9
